services:
  directus:
    image: directus/directus:10.13.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "K87wFirZn94PKPFyYYYi"
      ADMIN_EMAIL: "fyit-pos.admin@maartenlauwaert.eu"
      ADMIN_PASSWORD: "X6vmtiBUfuU26tvFcWVK"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"